using MountainWarehouse.EasyMWS.Enums;
using System;

namespace MountainWarehouse.EasyMWS.DTO
{
    /// <summary>
    /// SettlementReport details for a report which has already been generated by Amazon and is available for download.
    /// </summary>
    public class SettlementReportDetails
    {
        /// <summary>
        /// Settlement report type as provided by Amazon and mapped to Enum.
        /// </summary>
        public readonly string ReportType;

        /// <summary>
        /// ReportId field as provided by Amazon.
        /// </summary>
        public readonly string ReportId;

        /// <summary>
        /// IsAcknowledged field as provided by Amazon.
        /// </summary>
        public readonly bool IsAcknowledged;

        /// <summary>
        /// AvailableDate field as provided by Amazon.
        /// </summary>
        public readonly DateTime AvailableDate;

        public SettlementReportDetails(string reportType, string reportId, bool isAcknowledged, DateTime availableDate)
        {
            ReportType = reportType;
            ReportId = reportId;
            IsAcknowledged = isAcknowledged;
            AvailableDate = availableDate;
        }
    }
}
